<?php

/**
 * This is the model base class for the table "projecto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Projecto".
 *
 * Columns in table "projecto" available as properties of the model,
 * followed by relations of table "projecto" available as properties of the model.
 *
 * @property integer $id
 * @property string $descricao
 * @property string $data_inicio
 * @property string $data_fim
 * @property integer $duracao
 * @property string $ambito
 *
 * @property MembroProjecto[] $membroProjectos
 * @property Requisito[] $requisitos
 * @property Stakeholder[] $stakeholders
 */
abstract class BaseProjecto extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'projecto';
    }

    public static function representingColumn() {
        return 'descricao';
    }

    public function rules() {
        return array(
            array('descricao, data_inicio, data_fim, duracao, ambito', 'required'),
            array('duracao', 'numerical', 'integerOnly'=>true),
            array('descricao, ambito', 'length', 'max'=>100),
            array('id, descricao, data_inicio, data_fim, duracao, ambito', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'membroProjectos' => array(self::HAS_MANY, 'MembroProjecto', 'projecto'),
            'requisitos' => array(self::HAS_MANY, 'Requisito', 'projecto'),
            'stakeholders' => array(self::HAS_MANY, 'Stakeholder', 'projecto'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'descricao' => Yii::t('app', 'Descricao'),
                'data_inicio' => Yii::t('app', 'Data Inicio'),
                'data_fim' => Yii::t('app', 'Data Fim'),
                'duracao' => Yii::t('app', 'Duracao'),
                'ambito' => Yii::t('app', 'Ambito'),
                'membroProjectos' => null,
                'requisitos' => null,
                'stakeholders' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('descricao', $this->descricao, true);
        $criteria->compare('data_inicio', $this->data_inicio, true);
        $criteria->compare('data_fim', $this->data_fim, true);
        $criteria->compare('duracao', $this->duracao);
        $criteria->compare('ambito', $this->ambito, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}