<?php

/**
 * This is the model base class for the table "membro_caso".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MembroCaso".
 *
 * Columns in table "membro_caso" available as properties of the model,
 * followed by relations of table "membro_caso" available as properties of the model.
 *
 * @property integer $id
 * @property integer $membro
 * @property integer $caso_uso
 *
 * @property Membro $membro0
 * @property CasoUso $casoUso
 */
abstract class BaseMembroCaso extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'membro_caso';
    }

    public static function representingColumn() {
        return 'id';
    }

    public function rules() {
        return array(
            array('membro, caso_uso', 'required'),
            array('membro, caso_uso', 'numerical', 'integerOnly'=>true),
            array('id, membro, caso_uso', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'membro0' => array(self::BELONGS_TO, 'Membro', 'membro'),
            'casoUso' => array(self::BELONGS_TO, 'CasoUso', 'caso_uso'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'membro' => Yii::t('app', 'Membro'),
                'caso_uso' => Yii::t('app', 'Caso Uso'),
                'membro0' => null,
                'casoUso' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('membro', $this->membro);
        $criteria->compare('caso_uso', $this->caso_uso);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
    
    public function search_Membro($parentID) {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('membro', $parentID);
        $criteria->compare('caso_uso', $this->caso_uso);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
    
    public function search_Caso($parentID) {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('membro', $this->membro);
        $criteria->compare('caso_uso', $parentID);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}