<?php

/**
 * This is the model base class for the table "ecra_caso".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EcraCaso".
 *
 * Columns in table "ecra_caso" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $ecra
 * @property integer $caso_uso
 *
 */
abstract class BaseEcraCaso extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'ecra_caso';
    }

    public static function representingColumn() {
        return array(
            'ecra',
            'caso_uso',
        );
    }

    public function rules() {
        return array(
            array('ecra, caso_uso', 'required'),
            array('ecra, caso_uso', 'numerical', 'integerOnly'=>true),
            array('ecra, caso_uso', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'ecra' => Yii::t('app', 'Ecra'),
                'caso_uso' => Yii::t('app', 'Caso Uso'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('ecra', $this->ecra);
        $criteria->compare('caso_uso', $this->caso_uso);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}