<?php

/**
 * This is the model base class for the table "stakeholder_membro".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "StakeholderMembro".
 *
 * Columns in table "stakeholder_membro" available as properties of the model,
 * followed by relations of table "stakeholder_membro" available as properties of the model.
 *
 * @property integer $id
 * @property integer $stakeholder
 * @property integer $membro
 *
 * @property Stakeholder $stakeholder0
 * @property Membro $membro0
 */
abstract class BaseStakeholderMembro extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'stakeholder_membro';
    }

    public static function representingColumn() {
        return 'id';
    }

    public function rules() {
        return array(
            array('stakeholder, membro', 'required'),
            array('stakeholder, membro', 'numerical', 'integerOnly'=>true),
            array('id, stakeholder, membro', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'stakeholder0' => array(self::BELONGS_TO, 'Stakeholder', 'stakeholder'),
            'membro0' => array(self::BELONGS_TO, 'Membro', 'membro'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'stakeholder' => Yii::t('app', 'Stakeholder'),
                'membro' => Yii::t('app', 'Membro'),
                'stakeholder0' => null,
                'membro0' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('stakeholder', $this->stakeholder);
        $criteria->compare('membro', $this->membro);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
    
    public function search_Stakeholder($parentID) {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('stakeholder', $parentID);
        $criteria->compare('membro', $this->membro);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function search_Membro($parentID) {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('stakeholder', $this->stakeholder);
        $criteria->compare('membro', $parentID);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}