<?php

/**
 * This is the model base class for the table "requisitos".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Requisitos".
 *
 * Columns in table "requisitos" available as properties of the model,
 * followed by relations of table "requisitos" available as properties of the model.
 *
 * @property integer $cod_requisito
 * @property integer $projecto
 * @property string $descricao
 * @property integer $estado
 *
 * @property Alteracao[] $alteracaos
 * @property Projecto $projecto0
 * @property Estado $estado0
 * @property Stakeholder[] $stakeholders
 */
abstract class BaseRequisitos extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'requisitos';
    }

    public static function representingColumn() {
        return 'descricao';
    }

    public function rules() {
        return array(
            array('projecto, descricao, estado', 'required'),
            array('projecto, estado', 'numerical', 'integerOnly'=>true),
            array('descricao', 'length', 'max'=>100),
            array('cod_requisito, projecto, descricao, estado', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'alteracaos' => array(self::MANY_MANY, 'Alteracao', 'alteracoes_requisito(requisito, alteracao)'),
            'projecto0' => array(self::BELONGS_TO, 'Projecto', 'projecto'),
            'estado0' => array(self::BELONGS_TO, 'Estado', 'estado'),
            'stakeholders' => array(self::MANY_MANY, 'Stakeholder', 'requisitos_stakeholders(requisito, stakeholder)'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'cod_requisito' => Yii::t('app', 'Cod Requisito'),
                'projecto' => Yii::t('app', 'Projecto'),
                'descricao' => Yii::t('app', 'Descricao'),
                'estado' => Yii::t('app', 'Estado'),
                'alteracaos' => null,
                'projecto0' => null,
                'estado0' => null,
                'stakeholders' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('cod_requisito', $this->cod_requisito);
        $criteria->compare('projecto', $this->projecto);
        $criteria->compare('descricao', $this->descricao, true);
        $criteria->compare('estado', $this->estado);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}