<?php

/**
 * This is the model base class for the table "membros_caso_uso".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MembrosCasoUso".
 *
 * Columns in table "membros_caso_uso" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $membro
 * @property integer $caso_uso
 *
 */
abstract class BaseMembrosCasoUso extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'membros_caso_uso';
    }

    public static function representingColumn() {
        return array(
            'membro',
            'caso_uso',
        );
    }

    public function rules() {
        return array(
            array('membro, caso_uso', 'required'),
            array('membro, caso_uso', 'numerical', 'integerOnly'=>true),
            array('membro, caso_uso', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'membro' => Yii::t('app', 'Membro'),
                'caso_uso' => Yii::t('app', 'Caso Uso'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('membro', $this->membro);
        $criteria->compare('caso_uso', $this->caso_uso);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}