<?php

/**
 * This is the model base class for the table "membro".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Membro".
 *
 * Columns in table "membro" available as properties of the model,
 * followed by relations of table "membro" available as properties of the model.
 *
 * @property integer $id
 * @property string $descricao
 * @property integer $pessoa
 *
 * @property Pessoa $pessoa0
 * @property MembroCaso[] $membroCasos
 * @property MembroProjecto[] $membroProjectos
 * @property StakeholderMembro[] $stakeholderMembros
 */
abstract class BaseMembro extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'membro';
    }

    public static function representingColumn() {
        return 'descricao';
    }

    public function rules() {
        return array(
            array('descricao, pessoa', 'required'),
            array('pessoa', 'numerical', 'integerOnly'=>true),
            array('descricao', 'length', 'max'=>100),
            array('id, descricao, pessoa', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'pessoa0' => array(self::BELONGS_TO, 'Pessoa', 'pessoa'),
            'membroCasos' => array(self::HAS_MANY, 'MembroCaso', 'membro'),
            'membroProjectos' => array(self::HAS_MANY, 'MembroProjecto', 'membro'),
            'stakeholderMembros' => array(self::HAS_MANY, 'StakeholderMembro', 'membro'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'descricao' => Yii::t('app', 'Descricao'),
                'pessoa' => Yii::t('app', 'Pessoa'),
                'pessoa0' => null,
                'membroCasos' => null,
                'membroProjectos' => null,
                'stakeholderMembros' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('descricao', $this->descricao, true);
        $criteria->compare('pessoa', $this->pessoa);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}