<?php

/**
 * This is the model base class for the table "grupo_analise".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "GrupoAnalise".
 *
 * Columns in table "grupo_analise" available as properties of the model,
 * followed by relations of table "grupo_analise" available as properties of the model.
 *
 * @property integer $cod_grupo
 * @property string $descricao
 *
 * @property Stakeholder[] $stakeholders
 */
abstract class BaseGrupoAnalise extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'grupo_analise';
    }

    public static function representingColumn() {
        return 'descricao';
    }

    public function rules() {
        return array(
            array('descricao', 'required'),
            array('descricao', 'length', 'max'=>100),
            array('cod_grupo, descricao', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'stakeholders' => array(self::HAS_MANY, 'Stakeholder', 'grupo'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'cod_grupo' => Yii::t('app', 'Cod Grupo'),
                'descricao' => Yii::t('app', 'Descricao'),
                'stakeholders' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('cod_grupo', $this->cod_grupo);
        $criteria->compare('descricao', $this->descricao, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}