<?php

/**
 * This is the model base class for the table "stakeholder".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Stakeholder".
 *
 * Columns in table "stakeholder" available as properties of the model,
 * followed by relations of table "stakeholder" available as properties of the model.
 *
 * @property integer $id
 * @property string $descricao
 * @property integer $grupo
 * @property integer $cliente
 * @property integer $pessoa
 * @property integer $projecto
 *
 * @property Alteracao[] $alteracaos
 * @property Requisito[] $requisitos
 * @property Grupo $grupo0
 * @property Cliente $cliente0
 * @property Pessoa $pessoa0
 * @property Projecto $projecto0
 * @property Membro[] $membros
 */
abstract class BaseStakeholder extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'stakeholder';
    }

    public static function representingColumn() {
        return 'descricao';
    }

    public function rules() {
        return array(
            array('descricao, grupo, cliente, pessoa, projecto', 'required'),
            array('grupo, cliente, pessoa, projecto', 'numerical', 'integerOnly'=>true),
            array('descricao', 'length', 'max'=>100),
            array('id, descricao, grupo, cliente, pessoa, projecto', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'alteracaos' => array(self::HAS_MANY, 'Alteracao', 'stakeholder'),
            'requisitos' => array(self::MANY_MANY, 'Requisito', 'requisitos_stakeholders(stakeholder, requisito)'),
            'grupo0' => array(self::BELONGS_TO, 'Grupo', 'grupo'),
            'cliente0' => array(self::BELONGS_TO, 'Cliente', 'cliente'),
            'pessoa0' => array(self::BELONGS_TO, 'Pessoa', 'pessoa'),
            'projecto0' => array(self::BELONGS_TO, 'Projecto', 'projecto'),
            'membros' => array(self::MANY_MANY, 'Membro', 'stakeholder_membro(stakeholder, membro)'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'descricao' => Yii::t('app', 'Descricao'),
                'grupo' => Yii::t('app', 'Grupo'),
                'cliente' => Yii::t('app', 'Cliente'),
                'pessoa' => Yii::t('app', 'Pessoa'),
                'projecto' => Yii::t('app', 'Projecto'),
                'alteracaos' => null,
                'requisitos' => null,
                'grupo0' => null,
                'cliente0' => null,
                'pessoa0' => null,
                'projecto0' => null,
                'membros' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('descricao', $this->descricao, true);
        $criteria->compare('grupo', $this->grupo);
        $criteria->compare('cliente', $this->cliente);
        $criteria->compare('pessoa', $this->pessoa);
        $criteria->compare('projecto', $this->projecto);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
    
    public function search_Projecto($parentID) {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('descricao', $this->descricao, true);
        $criteria->compare('grupo', $this->grupo);
        $criteria->compare('cliente', $this->cliente);
        $criteria->compare('pessoa', $this->pessoa);
        $criteria->compare('projecto', $parentID);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}