<?php

/**
 * This is the model base class for the table "membro".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Membro".
 *
 * Columns in table "membro" available as properties of the model,
 * followed by relations of table "membro" available as properties of the model.
 *
 * @property integer $cod_membro
 * @property string $descricao
 * @property integer $pessoa
 *
 * @property Pessoa $pessoa0
 * @property CasoUso[] $casoUsos
 * @property Projecto[] $projectos
 * @property Stakeholder[] $stakeholders
 */
abstract class BaseMembro extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'membro';
    }

    public static function representingColumn() {
        return 'descricao';
    }

    public function rules() {
        return array(
            array('descricao, pessoa', 'required'),
            array('pessoa', 'numerical', 'integerOnly'=>true),
            array('descricao', 'length', 'max'=>100),
            array('cod_membro, descricao, pessoa', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'pessoa0' => array(self::BELONGS_TO, 'Pessoa', 'pessoa'),
            'casoUsos' => array(self::MANY_MANY, 'CasoUso', 'membros_caso_uso(membro, caso_uso)'),
            'projectos' => array(self::MANY_MANY, 'Projecto', 'membros_projecto(membro, projecto)'),
            'stakeholders' => array(self::MANY_MANY, 'Stakeholder', 'stakeholder_membro(membro, stakeholder)'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'cod_membro' => Yii::t('app', 'Cod Membro'),
                'descricao' => Yii::t('app', 'Descricao'),
                'pessoa' => Yii::t('app', 'Pessoa'),
                'pessoa0' => null,
                'casoUsos' => null,
                'projectos' => null,
                'stakeholders' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('cod_membro', $this->cod_membro);
        $criteria->compare('descricao', $this->descricao, true);
        $criteria->compare('pessoa', $this->pessoa);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}