<?php

/**
 * This is the model base class for the table "alteracao_requisito".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "AlteracaoRequisito".
 *
 * Columns in table "alteracao_requisito" available as properties of the model,
 * followed by relations of table "alteracao_requisito" available as properties of the model.
 *
 * @property integer $id
 * @property integer $alteracao
 * @property integer $requisito
 *
 * @property Alteracao $alteracao0
 * @property Requisito $requisito0
 */
abstract class BaseAlteracaoRequisito extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'alteracao_requisito';
    }

    public static function representingColumn() {
        return 'id';
    }

    public function rules() {
        return array(
            array('alteracao, requisito', 'required'),
            array('alteracao, requisito', 'numerical', 'integerOnly'=>true),
            array('id, alteracao, requisito', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'alteracao0' => array(self::BELONGS_TO, 'Alteracao', 'alteracao'),
            'requisito0' => array(self::BELONGS_TO, 'Requisito', 'requisito'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'alteracao' => Yii::t('app', 'Alteracao'),
                'requisito' => Yii::t('app', 'Requisito'),
                'alteracao0' => null,
                'requisito0' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('alteracao', $this->alteracao);
        $criteria->compare('requisito', $this->requisito);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
    
    public function search_Alteracao($parentID) {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('alteracao', $parentID);
        $criteria->compare('requisito', $this->requisito);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
    
    public function search_Requisito($parentID) {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('alteracao', $this->alteracao);
        $criteria->compare('requisito', $parentID);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}