<?php

/**
 * This is the model base class for the table "alteracao".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Alteracao".
 *
 * Columns in table "alteracao" available as properties of the model,
 * followed by relations of table "alteracao" available as properties of the model.
 *
 * @property integer $id
 * @property integer $stakeholder
 * @property string $data_alteracao
 * @property string $descricao
 *
 * @property Stakeholder $stakeholder0
 * @property AlteracaoRequisito[] $alteracaoRequisitos
 */
abstract class BaseAlteracao extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'alteracao';
    }

    public static function representingColumn() {
        return 'data_alteracao';
    }

    public function rules() {
        return array(
            array('stakeholder, data_alteracao, descricao', 'required'),
            array('stakeholder', 'numerical', 'integerOnly'=>true),
            array('descricao', 'length', 'max'=>250),
            array('id, stakeholder, data_alteracao, descricao', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'stakeholder0' => array(self::BELONGS_TO, 'Stakeholder', 'stakeholder'),
            'alteracaoRequisitos' => array(self::HAS_MANY, 'AlteracaoRequisito', 'alteracao'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'stakeholder' => Yii::t('app', 'Stakeholder'),
                'data_alteracao' => Yii::t('app', 'Data Alteracao'),
                'descricao' => Yii::t('app', 'Descricao'),
                'stakeholder0' => null,
                'alteracaoRequisitos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('stakeholder', $this->stakeholder);
        $criteria->compare('data_alteracao', $this->data_alteracao, true);
        $criteria->compare('descricao', $this->descricao, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
    
    public function search_Stakeholder($parentID) {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('stakeholder', $parentID);
        $criteria->compare('data_alteracao', $this->data_alteracao, true);
        $criteria->compare('descricao', $this->descricao, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}