<?php

/**
 * This is the model base class for the table "entidade".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Entidade".
 *
 * Columns in table "entidade" available as properties of the model,
 * followed by relations of table "entidade" available as properties of the model.
 *
 * @property integer $cod_entidade
 * @property string $nome
 * @property string $descricao
 *
 * @property CasoUso[] $casoUsos
 */
abstract class BaseEntidade extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'entidade';
    }

    public static function representingColumn() {
        return 'nome';
    }

    public function rules() {
        return array(
            array('nome, descricao', 'required'),
            array('nome', 'length', 'max'=>100),
            array('descricao', 'length', 'max'=>150),
            array('cod_entidade, nome, descricao', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'casoUsos' => array(self::MANY_MANY, 'CasoUso', 'entidade_caso(entidade, caso_uso)'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'cod_entidade' => Yii::t('app', 'Cod Entidade'),
                'nome' => Yii::t('app', 'Nome'),
                'descricao' => Yii::t('app', 'Descricao'),
                'casoUsos' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('cod_entidade', $this->cod_entidade);
        $criteria->compare('nome', $this->nome, true);
        $criteria->compare('descricao', $this->descricao, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}