<?php

/**
 * This is the model base class for the table "ecra_caso".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EcraCaso".
 *
 * Columns in table "ecra_caso" available as properties of the model,
 * followed by relations of table "ecra_caso" available as properties of the model.
 *
 * @property integer $id
 * @property integer $ecra
 * @property integer $caso_uso
 *
 * @property Ecra $ecra0
 * @property CasoUso $casoUso
 */
abstract class BaseEcraCaso extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'ecra_caso';
    }

    public static function representingColumn() {
        return 'id';
    }

    public function rules() {
        return array(
            array('ecra, caso_uso', 'required'),
            array('ecra, caso_uso', 'numerical', 'integerOnly'=>true),
            array('id, ecra, caso_uso', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'ecra0' => array(self::BELONGS_TO, 'Ecra', 'ecra'),
            'casoUso' => array(self::BELONGS_TO, 'CasoUso', 'caso_uso'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'ecra' => Yii::t('app', 'Ecra'),
                'caso_uso' => Yii::t('app', 'Caso Uso'),
                'ecra0' => null,
                'casoUso' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('ecra', $this->ecra);
        $criteria->compare('caso_uso', $this->caso_uso);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
    
    public function search_Ecra($parentID) {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('ecra', $parentID);
        $criteria->compare('caso_uso', $this->caso_uso);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
    
    public function search_Caso($parentID) {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('ecra', $this->ecra);
        $criteria->compare('caso_uso', $parentID);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}