<?php

/**
 * This is the model base class for the table "profiles".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Profiles".
 *
 * Columns in table "profiles" available as properties of the model,
 * followed by relations of table "profiles" available as properties of the model.
 *
 * @property integer $user_id
 * @property string $lastname
 * @property string $firstname
 *
 * @property Users $user
 */
abstract class BaseProfiles extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'profiles';
    }

    public static function representingColumn() {
        return 'lastname';
    }

    public function rules() {
        return array(
            array('lastname, firstname', 'length', 'max'=>50),
            array('lastname, firstname', 'default', 'setOnEmpty' => true, 'value' => null),
            array('user_id, lastname, firstname', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'user' => array(self::BELONGS_TO, 'Users', 'user_id'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'user_id' => Yii::t('app', 'User'),
                'lastname' => Yii::t('app', 'Lastname'),
                'firstname' => Yii::t('app', 'Firstname'),
                'user' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('user_id', $this->user_id);
        $criteria->compare('lastname', $this->lastname, true);
        $criteria->compare('firstname', $this->firstname, true);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}