<?php

/**
 * This is the model base class for the table "requisito_stakeholder".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RequisitoStakeholder".
 *
 * Columns in table "requisito_stakeholder" available as properties of the model,
 * followed by relations of table "requisito_stakeholder" available as properties of the model.
 *
 * @property integer $id
 * @property integer $requisito
 * @property integer $stakeholder
 *
 * @property Requisito $requisito0
 * @property Stakeholder $stakeholder0
 */
abstract class BaseRequisitoStakeholder extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'requisito_stakeholder';
    }

    public static function representingColumn() {
        return 'id';
    }

    public function rules() {
        return array(
            array('requisito, stakeholder', 'required'),
            array('requisito, stakeholder', 'numerical', 'integerOnly'=>true),
            array('id, requisito, stakeholder', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
            'requisito0' => array(self::BELONGS_TO, 'Requisito', 'requisito'),
            'stakeholder0' => array(self::BELONGS_TO, 'Stakeholder', 'stakeholder'),
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'id' => Yii::t('app', 'ID'),
                'requisito' => Yii::t('app', 'Requisito'),
                'stakeholder' => Yii::t('app', 'Stakeholder'),
                'requisito0' => null,
                'stakeholder0' => null,
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('requisito', $this->requisito);
        $criteria->compare('stakeholder', $this->stakeholder);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
    
    public function search_Requisito($parentID) {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('requisito', $parentID);
        $criteria->compare('stakeholder', $this->stakeholder);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }
    
    public function search_Stakeholder($parentID) {
        $criteria = new CDbCriteria;

        $criteria->compare('id', $this->id);
        $criteria->compare('requisito', $this->requisito);
        $criteria->compare('stakeholder', $parentID);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}