<?php

/**
 * This is the model base class for the table "membros_projecto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "MembrosProjecto".
 *
 * Columns in table "membros_projecto" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $projecto
 * @property integer $membro
 *
 */
abstract class BaseMembrosProjecto extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'membros_projecto';
    }

    public static function representingColumn() {
        return array(
            'projecto',
            'membro',
        );
    }

    public function rules() {
        return array(
            array('projecto, membro', 'required'),
            array('projecto, membro', 'numerical', 'integerOnly'=>true),
            array('projecto, membro', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'projecto' => Yii::t('app', 'Projecto'),
                'membro' => Yii::t('app', 'Membro'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('projecto', $this->projecto);
        $criteria->compare('membro', $this->membro);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}