<?php

/**
 * This is the model base class for the table "requisitos_stakeholders".
 * DO NOT MODIFY THIS FILE! It is automatically generated by AweCrud.
 * If any changes are necessary, you must set or override the required
 * property or method in class "RequisitosStakeholders".
 *
 * Columns in table "requisitos_stakeholders" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $requisito
 * @property integer $stakeholder
 *
 */
abstract class BaseRequisitosStakeholders extends AweActiveRecord {

    public static function model($className=__CLASS__) {
        return parent::model($className);
    }

    public function tableName() {
        return 'requisitos_stakeholders';
    }

    public static function representingColumn() {
        return array(
            'requisito',
            'stakeholder',
        );
    }

    public function rules() {
        return array(
            array('requisito, stakeholder', 'required'),
            array('requisito, stakeholder', 'numerical', 'integerOnly'=>true),
            array('requisito, stakeholder', 'safe', 'on'=>'search'),
        );
    }

    public function relations() {
        return array(
        );
    }

    /**
     * @return array customized attribute labels (name=>label)
     */
    public function attributeLabels() {
        return array(
                'requisito' => Yii::t('app', 'Requisito'),
                'stakeholder' => Yii::t('app', 'Stakeholder'),
        );
    }

    public function search() {
        $criteria = new CDbCriteria;

        $criteria->compare('requisito', $this->requisito);
        $criteria->compare('stakeholder', $this->stakeholder);

        return new CActiveDataProvider($this, array(
            'criteria' => $criteria,
        ));
    }

    public function behaviors() {
        return array_merge(array(
        ), parent::behaviors());
    }
}